#!/bin/sh
source /home/msq/gcc/environment-setup-cortexa7hf-neon-emtronix-linux-gnueabi
LIST=" \
	common dataproc up_proc ValveControl watchdog\
"
build_target(){
	cd $1
	make clean >/dev/null
	make
	cd ..
}

for target in $LIST
	do
		build_target ${target}
	done
