#!/bin/sh
LIST=" \
    common up_proc ValveControl autodial watchdog\
"
build_target(){
    cd $1
    make clean >/dev/null
    cd ..
}

for target in $LIST
    do
        build_target ${target}
    done
